os:
  - Visual Studio 2015 CTP
branches:
  only:
    - master
install:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
before_build:
  - mkdir Build
  - cd Build
  - cmake .. -G "Visual Studio 14"
build_script:
  - msbuild Singleton.sln /nologo /verbosity:minimal
test_script:
  - msbuild RUN_TESTS.vcxproj /nologo /verbosity:minimal
